-- User Conference Assignments Table
-- This table manages which users can manage which conferences

CREATE TABLE user_conference_assignments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    conference_id NUMBER NOT NULL,
    permissions CLOB, -- JSON string containing specific permissions for this conference
    assigned_by NUMBER NOT NULL, -- Admin who assigned this
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active NUMBER(1) DEFAULT 1, -- 1 = active, 0 = inactive
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraints
    CONSTRAINT fk_uca_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_uca_conference FOREIGN KEY (conference_id) REFERENCES conferences(id) ON DELETE CASCADE,
    CONSTRAINT fk_uca_assigned_by FOREIGN KEY (assigned_by) REFERENCES app_users(id),
    
    -- Unique constraint to prevent duplicate assignments
    CONSTRAINT uk_uca_user_conference UNIQUE (user_id, conference_id)
);

-- Indexes for better performance
CREATE INDEX idx_uca_user_id ON user_conference_assignments(user_id);
CREATE INDEX idx_uca_conference_id ON user_conference_assignments(conference_id);
CREATE INDEX idx_uca_active ON user_conference_assignments(is_active);

-- Comments
COMMENT ON TABLE user_conference_assignments IS 'Manages which users can manage which conferences';
COMMENT ON COLUMN user_conference_assignments.user_id IS 'ID of the user (staff member)';
COMMENT ON COLUMN user_conference_assignments.conference_id IS 'ID of the conference';
COMMENT ON COLUMN user_conference_assignments.permissions IS 'JSON string containing specific permissions for this conference';
COMMENT ON COLUMN user_conference_assignments.assigned_by IS 'ID of admin who assigned this';
COMMENT ON COLUMN user_conference_assignments.is_active IS 'Whether this assignment is active (1) or inactive (0)';

-- Sample data (optional - for testing)
-- INSERT INTO user_conference_assignments (user_id, conference_id, permissions, assigned_by) 
-- VALUES (2, 1, '{"conferences.view": true, "conferences.update": true, "attendees.manage": true}', 1);
